### ISSUE TITLE
Not working on starter

### ISSUE THREAD

**Issue by limelect** [lynatan/DLight#1]
With ver 3 still not working on starter

**Comment by superswanman** [comment]
Starter has no local variables evaluation, only watch expressions.
Watch expressions are not working too? It requires to add any expressions to the watch expressions window.

**Comment by limelect** [comment]
Oooops my mistake it seem to work. Thanks. I did not understand how it suppose to work.
P.S can the color be programmable.
The green is not to my liking.
Thanks
I think i will compile another color

Try 
    Canvas.Brush.Color :=clAqua; //clTeal;
    Canvas.Font.Color := clRed;//  clAqua;
I think it is nicer

**Comment by superswanman** [comment]
alright, I will add color option menu.
